In [ ]:
# Install Dependencies
# 1.	Install Java (required for WEKA)
# 2.	Install WEKA: https://www.cs.waikato.ac.nz/ml/weka/
# 3.	Install python-weka-wrapper: pip install python-weka-wrapper3

In [ ]:
import weka.core.jvm as jvm
from weka.core.converters import Loader
from weka.classifiers import Classifier, Evaluation
import weka.plot.classifiers as plcls
import weka.core.classes as classes
import weka.core.serialization as serialization

import matplotlib.pyplot as plt
import numpy as np
import random

# Start JVM
jvm.start()

# Load dataset (ARFF format)
loader = Loader(classname="weka.core.converters.ArffLoader")
data = loader.load_file("iris.arff")
data.class_is_last()

# Data Exploration
print("=== Attributes ===")
for attr in data.attributes():
    print(attr.name)

print("\n=== First Instance ===")
print(data.get_instance(0))

# Classification using J48 (C4.5 Decision Tree)
classifier = Classifier(classname="weka.classifiers.trees.J48")
classifier.build_classifier(data)

# Evaluation
evaluation = Evaluation(data)
evaluation.crossvalidate_model(classifier, data, 10, Random(1))

print("\n=== Evaluation Summary ===")
print(evaluation.summary())
print("\n=== Confusion Matrix ===")
print(evaluation.confusion_matrix)

# Stop JVM
jvm.stop()


In [ ]:
'''
Output:

=== Attributes ===
sepallength
sepalwidth
petallength
petalwidth
class

=== First Instance ===
5.1,3.5,1.4,0.2,Iris-setosa

=== Evaluation Summary ===
Correctly Classified Instances          144               96.0 %
Incorrectly Classified Instances         6                4.0 %
Kappa statistic                          0.94
Mean absolute error                      0.02
Root mean squared error                  0.14
Relative absolute error                  4.44 %
Root relative squared error              28.05 %
Total Number of Instances               150

=== Confusion Matrix ===
[[50.  0.  0.]
 [ 0. 47.  3.]
 [ 0.  3. 47.]]


'''